# Generated by Django 3.0.8 on 2020-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_duration',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
