# Generated by Django 3.0.8 on 2020-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200713_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_duration',
            field=models.DurationField(default='00:00'),
        ),
    ]
