# Generated by Django 3.0.8 on 2020-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200713_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_released_on',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
