# Generated by Django 3.0.8 on 2020-07-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200713_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
