# Generated by Django 3.0.8 on 2020-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_song_song_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
