# Generated by Django 3.0.8 on 2020-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_playlist_playlist_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist_song',
            options={'ordering': ['playlist_song_order']},
        ),
        migrations.AddField(
            model_name='playlist_song',
            name='playlist_song_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playlist_song',
            unique_together={('playlist_song_order',)},
        ),
    ]
