# Generated by Django 3.0.8 on 2020-07-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200714_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist_song',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='playlist_song',
            old_name='playlist_song_id',
            new_name='playlist_song',
        ),
    ]
